#!/bin/bash

# Artifactory configuration
ARTIFACTORY_URL="https://YOUR-ARTIFACTORY-URL/artifactory/"
USERNAME="YOUR-USERNAME"
PASSWORD="YOUR-PASSWORD"

# Function to list all repositories
function list_all_repositories() {
    # Construct the curl command to list all repositories
    curl -u "${USERNAME}:${PASSWORD}" -X GET "${ARTIFACTORY_URL}api/repositories" -k
}

# Function to list artifacts in a repository
function list_artifacts_in_repository() {
    local repo_key="$1"
    # Construct the curl command to list artifacts in the repository
    curl -u "${USERNAME}:${PASSWORD}" -X GET "${ARTIFACTORY_URL}api/storage/${repo_key}?list&deep=1" -H "Accept: application/json" -k
}

# Function to list artifacts that have never been downloaded using AQL
function list_never_downloaded_artifacts() {
    # AQL query to find artifacts that have never been downloaded
    local aql_query='items.find({
      "$or": [
        {"downloadCount": {"$eq": null}},
        {"downloadCount": {"$eq": 0}}
      ]
    })'
    
    # Construct the URL for the AQL search endpoint
    local aql_search_url="${ARTIFACTORY_URL}api/search/aql"

    # Execute the curl command to search for artifacts using AQL
    curl -u "${USERNAME}:${PASSWORD}" -X POST "${aql_search_url}" -H "Content-Type: text/plain" -d "${aql_query}" -k
}

# List all repositories
echo "List of all repositories:"
list_all_repositories

# List artifacts in each repository
echo -e "\nList of artifacts in each repository:"
repos=$(list_all_repositories | jq -r '.[].key')
for repo in $repos; do
    echo "Repository: $repo"
    list_artifacts_in_repository "$repo"
    echo "====="
done

# List artifacts that have never been downloaded
echo -e "\nArtifacts that have never been downloaded:"
list_never_downloaded_artifacts
